# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-07 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='batch_id',
        ),
        migrations.AddField(
            model_name='t_item',
            name='batch_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
